language: java
script: mvn package test -Popenshift
jdk:
- oraclejdk7
- openjdk7
deploy:
  provider: openshift
  user: zhfall@126.com
  password:
    secure: US4yDrRKh1mk5ODF4sJ8IrpiSbzHCcSCQZcS02NJQlqakzmVMQttTY1LGJE1mogFKmFfvUe2ylVF+GTfLdzvxjLWtieSmi/Zw3s6q9PL49TLH7GoeqzZDwjiV8jmezMEX0qidd/A734sjJ1E1UJgKokZH6yihsC1iyh8RJUURAs=
  app: forumapp
  domain: zhfall72
  on:
    repo: zhfall/forumapp-openshift
